services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - recsocial_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
    volumes:
      - neo4j_data:/data
    networks:
      - recsocial_network

volumes:
  mongodb_data:
  neo4j_data:

networks:
  recsocial_network: